services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6001:6379"
    command: [valkey-server, '--protected-mode', 'no']

  redis:
    image: redis:7.2
    ports:
      - "6002:6379"
    volumes:
      - '.:/workspace'
      - './data:/data'
    command: [redis-server]